### ISSUE TITLE
lots of docs missing

### ISSUE THREAD

**Issue by davidmoten** [jankotek/mapdb-site#1]
Hi
I'm looking for information on your queue implementations but have to use the google cached version of www.mapdb.org/doc/queues.html for instance. Big rewrite happening or did you accidentally leave stuff out?
Thanks for creating MapDB!!!

**Comment by jankotek** [comment]
Hi, I switched website and documentation to 3.0 branch. PDF documentation for 1.0 and 2.0 is here:
https://github.com/jankotek/mapdb-site/raw/34a4fb4443a5dab1491b78ac851d1767f679cb2d/_downloads/mapdb-manual.pdf
