### ISSUE TITLE
Link to documentation doesn't work

### ISSUE THREAD

**Issue by grossvater** [jankotek/mapdb-site#18]
401 Unauthorized message for https://jankotek.gitbooks.io/mapdb/content/

**Comment by rajatgoyal715** [comment]
Mentioned link works perfect now. Good to be closed.
![Screenshot from 2021-02-22 21-26-50](https://user-images.githubusercontent.com/18263409/108733779-ce133500-7554-11eb-8d8c-11384b966aaf.png)

**Comment by icreator** [comment]
Please update on site - redirect from  https://jankotek.gitbooks.io/mapdb/content/ to good URL

**Comment by icreator** [comment]
see https://www.baeldung.com/mapdb
